### ISSUE TITLE
WFdownloads 3.3 - downloads.php

### ISSUE THREAD

**Issue by Aminov81** [XoopsModules25x/wfdownloads#31] opened 2020-12-06 19:04 UTC
I can edit the files but the modifications are not made. I get this message : "A problem has occurred on our server" due those errors : 
- Undefined offset: 0 in the file /modules/wfdownloads/class/Utility.php, line 1485
- Call to a member function getVar() on null in the file /modules/wfdownloads/class/Utility.ph,p line 1486

**Comment by mambax7** [comment] 2020-12-06 19:07
Try to change the line 1484 to this:

```php
        if (null !== ($mimetypeObjs = $helper->getHandler('Mimetype')->getObjects($criteria))) {
```

**Comment by Aminov81** [comment] 2020-12-06 19:15
Sorry, just the line 1486 or the lines 1984-1492 ?

**Comment by mambax7** [comment] 2020-12-06 19:17
All the lines, so it looks like above.

**Comment by Aminov81** [comment] 2020-12-06 19:18
ok i get it better now.
One minute please..

**Comment by mambax7** [comment] 2020-12-06 19:20
Actually, change the whole function to this (starting in 1473:
```php
    public static function allowedMimetypes($fileName, $isAdmin = true)
    {
        $helper = Helper::getInstance();

        $ext      = \ltrim(mb_strrchr($fileName, '.'), '.');
        $criteria = new \CriteriaCompo(new \Criteria('mime_ext', mb_strtolower($ext)));
        if ($isAdmin) {
            $criteria->add(new \Criteria('mime_admin', true));
        } else {
            $criteria->add(new \Criteria('mime_user', true));
        }
        $ret = [];
        if (false !== ($mimetypeObjs = $helper->getHandler('Mimetype')->getObjects($criteria))) {
            $mimetypeObj = $mimetypeObjs[0];
            if (null !== $mimetypeObj) {
                $ret = \explode(' ', $mimetypeObj->getVar('mime_types'));
            }
        }
        return $ret;
    }
```

**Comment by Aminov81** [comment] 2020-12-06 19:23
ok.

**Comment by Aminov81** [comment] 2020-12-06 19:28
Perfect, it worked :)

**Comment by Aminov81** [comment] 2020-12-06 19:29
I still have only this problem with old downloads inherited from the old version of the module.
Error: Call to a member function getVar() on integer dans le fichier /modules/wfdownloads/admin/downloads.php ligne 253

**Comment by mambax7** [comment] 2020-12-14 05:05
When does this happen? Can you share the link that you're using that causes that? 
Right now I can't reproduce it

**Comment by Aminov81** [comment] 2020-12-14 15:36
Here is the link : /modules/wfdownloads/admin/downloads.php?op=download.edit&lid=124
Try to edit the document with the id 124
![capture](https://user-images.githubusercontent.com/72750247/102101144-8bcdc900-3e2a-11eb-8482-6ff634d94e0b.png)

**Comment by alain01** [comment] 2020-12-14 15:42
Aminov,
please dont show your IP from Talborjt ;-)
Better for you.

**Comment by Aminov81** [comment] 2020-12-14 16:46
Thanks Alain. I didn't pay attention that my IP was on the screenshot !
But don't worry it's dynamic IP because i am not using ADSL connection ;-)

**Comment by mambax7** [comment] 2020-12-16 10:29
This should be now fixed in https://github.com/mambax7/wfdownloads/commit/a612b3a154d8a8758d1dd14660087fda2d919e17

**Comment by Aminov81** [comment] 2020-12-16 12:04
Perfect, it works fine now ;)

**Closed** 2020-12-16 12:04 UTC
