### ISSUE TITLE
WFdownloads - Pages title

### ISSUE THREAD

**Issue by Aminov81** [XoopsModules25x/wfdownloads#33] opened 2020-12-06 19:48 UTC
All pages generated by the module have as title the name of the module (wfdownloads) instead of having the title of each download.

**Comment by mambax7** [comment] 2020-12-07 19:16
I can't reproduce it here.
When I go to: modules/wfdownloads/singlefile.php?cid=1&lid=1, this is what I have, showing the name of the Category, and then the name of the download item:

![image](https://user-images.githubusercontent.com/613686/101394584-bd78ea00-3896-11eb-8975-dfb737bf3428.png)

**Comment by Aminov81** [comment] 2020-12-07 19:46
Sorry i was talking about the title tag.
On all pages i have this when i go to the source code.
<title>WFdownloads</title>

**Comment by mambax7** [comment] 2020-12-07 19:56
That's the title of the module. 

Are you using the tag anywhere in your theme? It should not be normally visible

**Comment by Aminov81** [comment] 2020-12-07 19:59
Here what i am using in my theme : 
<title><{if $xoops_pagetitle ==''}><{$xoops_sitename}><{/if}><{$xoops_pagetitle}></title>
And it's working fine with the 3.2 version.

**Comment by mambax7** [comment] 2020-12-07 20:01
Can you show a screenshot of the result in 3.2 version?

**Comment by Aminov81** [comment] 2020-12-07 20:03
Ok one minute please.

**Comment by Aminov81** [comment] 2020-12-07 20:12
How can i do to insert image here ?

**Comment by mambax7** [comment] 2020-12-07 20:18
Just paste it with Ctrl-V

**Comment by Aminov81** [comment] 2020-12-07 20:20
![Capture](https://user-images.githubusercontent.com/72750247/101400998-fc786100-38d1-11eb-97d5-913b91ce875c.PNG)

**Comment by Aminov81** [comment] 2020-12-07 20:34
The page title is the same as the file title, and each page has his own title (which is the file title related to).

**Comment by mambax7** [comment] 2020-12-14 06:21
It should be fixed now in https://github.com/mambax7/wfdownloads/commit/f0d47dc4dfad9b8c04d4608ee27e4563b855a0a7
Please re-open, if you still have issues

**Comment by Aminov81** [comment] 2020-12-14 15:28
It shows up the tile of the file but it adds the module name at the end of the page title.
It shouldn't (for SEO reasons) !
PS : I can't reopen this issue on my own, beacuse it was closed by the owner of the repository :-)

**Comment by mambax7** [comment] 2020-12-16 10:31
Try to change line 86:

```php
$xoopsTpl->assign('xoops_pagetitle', $downloadObj->getVar('title') . ' | ' . $helper->getModule()->name());
```

to 

```php
$xoopsTpl->assign('xoops_pagetitle', $downloadObj->getVar('title');
```

and see if it helps you

**Comment by Aminov81** [comment] 2020-12-16 11:34
I get this error now :
HTTP ERROR 500

**Comment by Aminov81** [comment] 2020-12-16 11:44
Actually there was an ")" missing before ";" 
$xoopsTpl->assign('xoops_pagetitle', $downloadObj->getVar('title')**)**;

**Comment by mambax7** [comment] 2020-12-16 11:49
Sorry for the typo. 
I'll look into the viewcat.php

**Comment by mambax7** [comment] 2020-12-17 10:14
You can set now the "short page titles" in your Preferences (it's at the bottom):
![image](https://user-images.githubusercontent.com/613686/102474562-ca2fd780-4026-11eb-9588-ee8d13905c86.png)

**Comment by Aminov81** [comment] 2020-12-17 15:12
It's practical solution for both sides, those who want to see the module name at the end of the page title and those who did not.
Is there any possibility on Github to select the files to download.
I want download only the 4 changed files, but i don't how to do it.

**Comment by zyspec** [comment] 2021-06-01 19:05
Issue appears to be closed. Please re-open or submit new issue if not resolved to your satisfaction

**Closed by zyspec** 2021-06-01 19:05 UTC
Labels: enhancement
