### ISSUE TITLE
WFdownloads 3.3 Beta 2 - Feedback

### ISSUE THREAD

**Issue by Aminov81** [XoopsModules25x/wfdownloads#26] opened 2020-12-04 15:24 UTC
Hey Michael :)
I hope you're well and thank you so much for what you're doing for the community..
I tested the new beta version of Wfdownloads module and here is my feedback :
1.  Undefined variable: imagearray in file /modules/wfdownloads/admin/downloads.php ligne 221
2. Error: Call to a member function getVar() on integer in file /modules/wfdownloads/admin/downloads.php ligne 248
3. Undefined variable: Request in file /modules/wfdownloads/admin/downloads.php ligne 385
4. Error: Class name must be a valid object or a string dans le fichier /modules/wfdownloads/admin/downloads.php ligne 385
5. All the categories are empty (so the downloads are not assigned to their catagories)
6. The download of files is impossible : the page "modules/wfdownloads/visit.php" is inaccessible (ERR_INVALID_RESPONSE) .
And there is also those warnings : 
- Use of undefined constant _MI_WFDOWNLOADS_DISPLAYTYPE_CATVIEW - assumed '_MI_WFDOWNLOADS_DISPLAYTYPE_CATVIEW' (this will throw an Error in a future version of PHP) dans le fichier /modules/wfdownloads/xoops_version.php ligne 360
- Use of undefined constant _MI_WFDOWNLOADS_DISPLAYTYPE_SUMMARY - assumed '_MI_WFDOWNLOADS_DISPLAYTYPE_SUMMARY' (this will throw an Error in a future version of PHP) dans le fichier /modules/wfdownloads/xoops_version.php ligne 361
- Use of undefined constant _MI_WFDOWNLOADS_DISPLAYTYPE_FULL - assumed '_MI_WFDOWNLOADS_DISPLAYTYPE_FULL' (this will throw an Error in a future version of PHP) dans le fichier /modules/wfdownloads/xoops_version.php ligne 362
- Use of undefined constant _MI_WFDOWNLOADS_DISPLAYTYPE_LIST - assumed '_MI_WFDOWNLOADS_DISPLAYTYPE_LIST' (this will throw an Error in a future version of PHP) dans le fichier /modules/wfdownloads/xoops_version.php ligne 363
- Use of undefined constant _MI_WFDOWNLOADS_DISPLAYTYPE_WFSECTION - assumed '_MI_WFDOWNLOADS_DISPLAYTYPE_WFSECTION' (this will throw an Error in a future version of PHP) dans le fichier /modules/wfdownloads/xoops_version.php ligne 364
- Use of undefined constant _MI_WFDOWNLOADS_DISPLAYTYPE_LEGACY - assumed '_MI_WFDOWNLOADS_DISPLAYTYPE_LEGACY' (this will throw an Error in a future version of PHP) dans le fichier /modules/wfdownloads/xoops_version.php ligne 365
My best regards and stay safe for us ;-)

**Comment by Aminov81** [comment] 2020-12-04 16:23
Sorry I almost forgot !
Here is my environment : XOOPS 2.5.10 / PHP | 7.2.33 / Mysql 5.5-10.1.46-MariaDB-cll-lve

**Comment by mambax7** [comment] 2020-12-05 08:54
All the constants like _MI_WFDOWNLOADS_DISPLAYTYPE_CATVIEW are present here in the English version. 
Maybe they are missing in the French version? Please compare the 
/language/english/modinfo.php 
with the 
/language/french/modinfo.php
and see if they have the same number of language constants. If not, please copy them from the English version

I'll check on the other issues this weekend....

**Comment by mambax7** [comment] 2020-12-05 12:17
Please take a look at the 3.30 Beta 3 and let me know if it's better:
https://github.com/mambax7/wfdownloads/releases/tag/3.30_Beta-3

**Comment by cesagonchu** [comment] 2020-12-05 13:43
Yes, I will translate, thx! 👍

**Comment by Aminov81** [comment] 2020-12-05 16:30
- The issue n° 5 is resolved. Now the downloads are assigned to their categories; However, i noticed that there is a problem whith the "pagenav" class.
For example the link of the second page of a given category (when we set 5 files per page), instead of being like this : "/modules/wfdownloads/viewcat.php?cid=1&start=6", i have this : "/modules/wfdownloads/viewcat.php?start=5&list=".

**Comment by Aminov81** [comment] 2020-12-05 16:33
Regarding the issue 1 and 2, i noticed that the problem occures only for the old downloads inherited from my old version of wfdownloads (when i try to edit them). But no problem for the new downloads created after updating the module.

**Comment by Aminov81** [comment] 2020-12-05 16:38
The issue n°6 is still here and the download of files is still impossible : the page "modules/wfdownloads/visit.php" is inaccessible (ERR_INVALID_RESPONSE).
This issue concerns only the files. When there is just an external link the redirection is done well.

**Comment by Aminov81** [comment] 2020-12-05 16:49
"Brokenfile.php" is inaccessible due to this error : 
 Class 'XoopsUserUtility' not found in the file /modules/wfdownloads/brokenfile.php ligne 200

**Comment by mambax7** [comment] 2020-12-05 18:20
Some of it I can't reproduce it here, but I'll take a closer look over the weekend...

**Comment by mambax7** [comment] 2020-12-05 18:30
Also, could you in the future create for each issue a separate report? That makes easier to track it. 
And thank you again for testing and reporting!

**Comment by Aminov81** [comment] 2020-12-05 18:58
Sorry, i didn't want to open a lot of reports. I thought it would be hard to handle but you have totally right, tracking will be more easy if report is open for each issue separately.
I'll take care of it tomorrow.

**Comment by Aminov81** [comment] 2020-12-05 19:04
Excuse me, what did you mean by "can't reproduce it here" ?
I didn't understand the meaning of the verb "reproduce" in the context used for.

**Comment by mambax7** [comment] 2020-12-05 19:13
Reproduce means to repeat the error/bug on my computer, so I could fix it. 
I'll work over the weekend on it, and I'll let you know...

**Comment by Aminov81** [comment] 2020-12-05 19:24
Thanks, i get it now :-)

**Comment by mambax7** [comment] 2020-12-06 09:01
Please download this latest version, test it, and let me know if it's better:
https://github.com/mambax7/wfdownloads/archive/master.zip

Please document separately all issues (old and new), so then I can address them one by one...
Thanks for your patience!!!

**Comment by mambax7** [comment] 2020-12-06 19:14
I will close it now, so please create separate new issue for any new bugs or that are still open

**Closed by mambax7** 2020-12-06 19:14 UTC
